version: "3"
services:
  db:
    image: mongo:latest
    ports:
      - 2717:27017
    networks:
      - private
  node:
    image: node:latest
    user: node
    working_dir: /home/node/app
    environment:
      NODE_ENV: production
      PORT: 8080
      DB_URL: ${DB_URL}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_EMAIL: admin@localhost
      ADMIN_PASSWORD: changeme
    volumes:
      - ./:/home/node/app
    expose:
      - 8080
    ports:
      - 80:8080
    command: npm start
    depends_on:
      - db
    networks:
      - public
      - private
networks:
  public:
    internal: false
  private:
    internal: true
